// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

export const GATEWAY_RESTART_MARKERS = Object.freeze({
  ROOT_EXEC_UNAVAILABLE: "ROOT_EXEC_UNAVAILABLE",
  GOSU_MISSING: "GOSU_MISSING",
  GATEWAY_USER_MISSING: "GATEWAY_USER_MISSING",
  SECRET_BOUNDARY_REFUSED: "SECRET_BOUNDARY_REFUSED",
  SECRET_BOUNDARY_OK: "SECRET_BOUNDARY_OK",
  SECRET_BOUNDARY_VALIDATOR_MISSING: "SECRET_BOUNDARY_VALIDATOR_MISSING",
  HERMES_RUNTIME_CONFIG_GUARD_MISSING: "HERMES_RUNTIME_CONFIG_GUARD_MISSING",
  HERMES_UNSAFE_CONFIG_PATH: "HERMES_UNSAFE_CONFIG_PATH",
  HERMES_LOCKED_HASH_MISMATCH: "HERMES_LOCKED_HASH_MISMATCH",
  GATEWAY_STALE_PROCESSES: "GATEWAY_STALE_PROCESSES",
  GATEWAY_FAILED: "GATEWAY_FAILED",
} as const);
